Repository Getbeans/Beans, pull requests merged in 2018-05, with the labels that each got.

#216 Improved accessibility of icons
  lib/templates/fragments/comments.php
  lib/templates/fragments/menu.php
  lib/templates/fragments/post.php
  lib/templates/fragments/searchform.php
  license.txt
Labels: Accessibility

#219 Improvements to Beans Compiler test suite.
  tests/phpunit/integration/api/compiler/beans-compiler/addContentMediaQuery.php
  tests/phpunit/integration/api/compiler/beans-compiler/cacheFile.php
  tests/phpunit/integration/api/compiler/beans-compiler/combineFragments.php
  tests/phpunit/integration/api/compiler/beans-compiler/fileystem.php
  tests/phpunit/integration/api/compiler/beans-compiler/formatContent.php
  tests/phpunit/integration/api/compiler/beans-compiler/getInternalContent.php
  tests/phpunit/integration/api/compiler/beans-compiler/getRemoteContent.php
  tests/phpunit/integration/api/compiler/beans-compiler/replaceCssUrl.php
  tests/phpunit/integration/api/compiler/beans-compiler/runCompiler.php
  tests/phpunit/integration/api/compiler/beans-compiler/setFilename.php
  tests/phpunit/integration/api/compiler/includes/class-compiler-test-case.php
  tests/phpunit/unit/api/compiler/beans-compiler/addContentMediaQuery.php
  tests/phpunit/unit/api/compiler/beans-compiler/cacheFile.php
  tests/phpunit/unit/api/compiler/beans-compiler/cacheFileExist.php
  tests/phpunit/unit/api/compiler/beans-compiler/combineFragments.php
  tests/phpunit/unit/api/compiler/beans-compiler/fileystem.php
  tests/phpunit/unit/api/compiler/beans-compiler/formatContent.php
  tests/phpunit/unit/api/compiler/beans-compiler/get.php
  tests/phpunit/unit/api/compiler/beans-compiler/getExtension.php
  tests/phpunit/unit/api/compiler/beans-compiler/getFunctionContent.php
  tests/phpunit/unit/api/compiler/beans-compiler/getInternalContent.php
  tests/phpunit/unit/api/compiler/beans-compiler/getRemoteContent.php
  tests/phpunit/unit/api/compiler/beans-compiler/replaceCssUrl.php
  tests/phpunit/unit/api/compiler/beans-compiler/runCompiler.php
  tests/phpunit/unit/api/compiler/beans-compiler/setFilename.php
  tests/phpunit/unit/api/compiler/beans-compiler/setFragments.php
  tests/phpunit/unit/api/compiler/includes/class-compiler-test-case.php
Labels: Testing

#222 Assigned `func_get_args()` to variable before passing to function.
  lib/api/html/functions.php
Labels: Bug

#224 Improved & Tested Page Compiler
  lib/api/compiler/class-beans-page-compiler.php
  lib/api/compiler/class-page-compiler.php
  lib/api/compiler/functions.php
  lib/api/compiler/views/localized-content.php
  lib/api/components.php
  tests/phpunit/integration/api/compiler/beans-page-compiler/compilePageScripts.php
  tests/phpunit/integration/api/compiler/beans-page-compiler/compilePageStyles.php
  tests/phpunit/integration/api/compiler/beans-page-compiler/dequeueScripts.php
  tests/phpunit/integration/api/compiler/includes/class-compiler-test-case.php
  tests/phpunit/integration/api/compiler/includes/class-page-compiler-test-case.php
  tests/phpunit/unit/api/compiler/beans-page-compiler/compilePageScripts.php
  tests/phpunit/unit/api/compiler/beans-page-compiler/compilePageStyles.php
  tests/phpunit/unit/api/compiler/beans-page-compiler/dequeueScripts.php
  tests/phpunit/unit/api/compiler/includes/class-compiler-options-test-case.php
  tests/phpunit/unit/api/compiler/includes/class-page-compiler-test-case.php
Labels: Compliance, Optimization, Quality, Testing

#226 Adds a Beans Test Resetter & Fixes CSS Minifier.
  lib/api/compiler/class-beans-compiler.php
  tests/phpunit/class-beans-resetter.php
  tests/phpunit/functions.php
  tests/phpunit/integration/api/compiler/beans-compiler/formatContent.php
  tests/phpunit/integration/api/compiler/includes/class-compiler-test-case.php
  tests/phpunit/integration/api/fields/beansField.php
  tests/phpunit/integration/api/filters/beansAddAnonymousFilter.php
  tests/phpunit/integration/api/filters/beansAddFilter.php
  tests/phpunit/integration/api/filters/beansApplyFilters.php
  tests/phpunit/integration/api/filters/beansHasFilters.php
  tests/phpunit/integration/api/options/beans-options/renderMetabox.php
  tests/phpunit/integration/api/template/beansLoadDefaultTemplate.php
  tests/phpunit/integration/api/template/beansLoadFragmentFile.php
  tests/phpunit/integration/api/term-meta/beans-term-meta/renderFields.php
  tests/phpunit/integration/api/term-meta/fixtures/test-field-outout-html.php
  tests/phpunit/integration/api/term-meta/includes/class-beans-term-meta-test-case.php
  tests/phpunit/integration/bootstrap.php
  tests/phpunit/integration/class-test-case.php
  tests/phpunit/test-case-trait.php
  tests/phpunit/unit/api/compiler/beans-compiler/combineFragments.php
  tests/phpunit/unit/api/compiler/beans-compiler/formatContent.php
  tests/phpunit/unit/api/compiler/beans-compiler/getInternalContent.php
  tests/phpunit/unit/api/compiler/includes/class-compiler-test-case.php
  tests/phpunit/unit/api/fields/includes/class-fields-test-case.php
  tests/phpunit/unit/api/filters/beansAddFilter.php
  tests/phpunit/unit/api/filters/beansApplyFilters.php
  tests/phpunit/unit/api/filters/beansHasFilters.php
  tests/phpunit/unit/api/template/beansLoadDefaultTemplate.php
  tests/phpunit/unit/api/template/beansLoadFragmentFile.php
  tests/phpunit/unit/api/term-meta/beans-term-meta/renderFields.php
  tests/phpunit/unit/api/term-meta/includes/class-beans-term-meta-test-case.php
  tests/phpunit/unit/api/utilities/beansGet.php
  tests/phpunit/unit/api/utilities/beansIsUrl.php
  tests/phpunit/unit/api/utilities/beansMultiArrayKeyExists.php
  tests/phpunit/unit/api/utilities/beansPathToUrl.php
  tests/phpunit/unit/api/utilities/beansRemoveDir.php
  tests/phpunit/unit/api/utilities/beansRenderFunction.php
  tests/phpunit/unit/api/utilities/beansRenderFunctionArray.php
  tests/phpunit/unit/api/utilities/beansSanitizePath.php
  tests/phpunit/unit/api/utilities/beansUrlToPath.php
  tests/phpunit/unit/bootstrap.php
  tests/phpunit/unit/class-test-case.php
Labels: Optimization, Testing

#238 Fixes the Template API to mock wp_head() & Clarifies intent.
  tests/phpunit/integration/api/template/beansLoadDefaultTemplate.php
  tests/phpunit/unit/api/template/beansLoadDefaultTemplate.php
Labels: Testing
