Repository Getbeans/Beans, pull requests merged in 2018-03, with the labels that each got.

#150 Add tests for beans_get_term_meta()
  lib/api/term-meta/functions.php
  tests/phpunit/integration/api/term-meta/beansGetTermMeta.php
  tests/phpunit/unit/api/term-meta/beansGetTermMeta.php
Labels: Compliance, Documentation, Testing

#118 Made Layout API WPCS compliant & tested.
  lib/api/layout/functions.php
  tests/phpunit/integration/api/layout/beansGetDefaultLayout.php
  tests/phpunit/integration/api/layout/beansGetLayout.php
  tests/phpunit/integration/api/layout/beansGetLayoutClass.php
  tests/phpunit/unit/api/layout/beansGetDefaultLayout.php
  tests/phpunit/unit/api/layout/beansGetLayout.php
  tests/phpunit/unit/api/layout/beansGetLayoutClass.php
Labels: Compliance, Documentation, Testing

#152 Added load original functions before monkey patch.
  tests/phpunit/unit/api/layout/beansGetDefaultLayout.php
  tests/phpunit/unit/api/layout/beansGetLayout.php
  tests/phpunit/unit/api/layout/beansGetLayoutClass.php
  tests/phpunit/unit/class-test-case.php
Labels: Testing

#154 Load original functions after initializing Patchwork.
  tests/phpunit/unit/api/actions/includes/class-actions-test-case.php
  tests/phpunit/unit/api/fields/includes/class-fields-test-case.php
  tests/phpunit/unit/api/filters/includes/class-filters-test-case.php
  tests/phpunit/unit/api/html/includes/class-html-test-case.php
  tests/phpunit/unit/api/post-meta/beansGetPostMeta.php
  tests/phpunit/unit/api/template/includes/class-template-test-case.php
  tests/phpunit/unit/api/term-meta/beansGetTermMeta.php
Labels: Testing

#149 Improved the tests for HTML Attributes.
  lib/api/html/class-beans-attribute.php
  lib/api/html/functions.php
  tests/phpunit/integration/api/html/beans-attribute/init.php
  tests/phpunit/integration/api/html/beansAddAttribute.php
  tests/phpunit/integration/api/html/beansIsHtmlDevMode.php
  tests/phpunit/integration/api/html/beansRemoveAttribute.php
  tests/phpunit/integration/api/html/beansReplaceAttribute.php
  tests/phpunit/unit/api/html/beans-attribute/add.php
  tests/phpunit/unit/api/html/beans-attribute/init.php
  tests/phpunit/unit/api/html/beans-attribute/remove.php
  tests/phpunit/unit/api/html/beans-attribute/replace.php
  tests/phpunit/unit/api/html/beansAddAttribute.php
  tests/phpunit/unit/api/html/beansIsHtmlDevMode.php
  tests/phpunit/unit/api/html/beansRemoveAttribute.php
  tests/phpunit/unit/api/html/beansReplaceAttribute.php
Labels: Testing

#116 Made _Beans_Image_Editor, beans_edit_image, & beans_get_images_dir WPCS compliant and tested.
  lib/api/image/class-beans-image-editor.php
  lib/api/image/class-images.php
  lib/api/image/functions.php
  tests/phpunit/integration/api/image/beans-image-editor/createEditedImage.php
  tests/phpunit/integration/api/image/beans-image-editor/run.php
  tests/phpunit/integration/api/image/beansEditImage.php
  tests/phpunit/integration/api/image/beansGetImagesDir.php
  tests/phpunit/integration/api/image/fixtures/image1.jpg
  tests/phpunit/integration/api/image/fixtures/image2.jpg
  tests/phpunit/integration/api/image/includes/class-image-test-case.php
  tests/phpunit/unit/api/image/beans-image-editor/createEditedImage.php
  tests/phpunit/unit/api/image/beans-image-editor/run.php
  tests/phpunit/unit/api/image/beansEditImage.php
  tests/phpunit/unit/api/image/beansGetImagesDir.php
  tests/phpunit/unit/api/image/fixtures/image1.jpg
  tests/phpunit/unit/api/image/fixtures/image2.jpg
  tests/phpunit/unit/api/image/includes/class-image-test-case.php
Labels: Compliance, Documentation, Optimization, Testing

#158 Improved Image API unit tests.
  lib/api/image/class-beans-image-editor.php
  tests/phpunit/integration/api/image/beans-image-editor/createEditedImage.php
  tests/phpunit/integration/api/image/beans-image-editor/run.php
  tests/phpunit/integration/api/image/beansEditImage.php
  tests/phpunit/integration/api/image/beansGetImagesDir.php
  tests/phpunit/unit/api/image/beans-image-editor/createEditedImage.php
  tests/phpunit/unit/api/image/beans-image-editor/run.php
  tests/phpunit/unit/api/image/beansEditImage.php
  tests/phpunit/unit/api/image/beansGetImagesDir.php
  tests/phpunit/unit/api/image/includes/class-image-test-case.php
Labels: Testing

#159 Improved Actions API tests.
  tests/phpunit/integration/api/actions/beansAddAction.php
  tests/phpunit/integration/api/actions/beansAddAnonymousAction.php
  tests/phpunit/integration/api/actions/beansModifyAction.php
  tests/phpunit/integration/api/actions/beansModifyActionArguments.php
  tests/phpunit/integration/api/actions/beansModifyActionCallback.php
  tests/phpunit/integration/api/actions/beansModifyActionHook.php
  tests/phpunit/integration/api/actions/beansModifyActionPriority.php
  tests/phpunit/integration/api/actions/beansRemoveAction.php
  tests/phpunit/integration/api/actions/beansReplaceAction.php
  tests/phpunit/integration/api/actions/beansReplaceActionArguments.php
  tests/phpunit/integration/api/actions/beansReplaceActionCallback.php
  tests/phpunit/integration/api/actions/beansReplaceActionHook.php
  tests/phpunit/integration/api/actions/beansReplaceActionPriority.php
  tests/phpunit/integration/api/actions/beansResetAction.php
  tests/phpunit/integration/api/actions/includes/class-actions-test-case.php
  tests/phpunit/integration/api/actions/includes/class-replace-action-test-case.php
  tests/phpunit/unit/api/actions/beansAddAction.php
  tests/phpunit/unit/api/actions/beansAddAnonymousAction.php
  tests/phpunit/unit/api/actions/beansBuildActionArray.php
  tests/phpunit/unit/api/actions/beansGetAction.php
  tests/phpunit/unit/api/actions/beansGetCurrentAction.php
  tests/phpunit/unit/api/actions/beansMergeAction.php
  tests/phpunit/unit/api/actions/beansModifyAction.php
  tests/phpunit/unit/api/actions/beansModifyActionArguments.php
  tests/phpunit/unit/api/actions/beansModifyActionCallback.php
  tests/phpunit/unit/api/actions/beansModifyActionHook.php
  tests/phpunit/unit/api/actions/beansModifyActionPriority.php
  tests/phpunit/unit/api/actions/beansRemoveAction.php
  tests/phpunit/unit/api/actions/beansRenderAction.php
  tests/phpunit/unit/api/actions/beansReplaceAction.php
  tests/phpunit/unit/api/actions/beansReplaceActionArguments.php
  tests/phpunit/unit/api/actions/beansReplaceActionCallback.php
  tests/phpunit/unit/api/actions/beansReplaceActionHook.php
  tests/phpunit/unit/api/actions/beansReplaceActionPriority.php
  tests/phpunit/unit/api/actions/beansResetAction.php
  tests/phpunit/unit/api/actions/beansSetAction.php
  tests/phpunit/unit/api/actions/beansUniqueActionId.php
  tests/phpunit/unit/api/actions/beansUnsetAction.php
  tests/phpunit/unit/api/actions/includes/class-actions-test-case.php
Labels: Testing

#167 Added full integration tests for Fields API
  tests/phpunit/integration/api/fields/beansField.php
  tests/phpunit/integration/api/fields/beansGetFields.php
  tests/phpunit/integration/api/fields/includes/class-fields-test-case.php
  tests/phpunit/integration/class-test-case.php
Labels: Testing

#170 Tested & Optimized beans_add_attributes.
  lib/api/html/functions.php
  tests/phpunit/integration/api/html/beansAddAttributes.php
  tests/phpunit/integration/api/html/includes/class-html-test-case.php
  tests/phpunit/unit/api/html/beansAddAttributes.php
  tests/phpunit/unit/api/html/includes/class-html-test-case.php
Labels: Optimization, Testing

#168 Tested & improved _Beans_Options
  lib/api/options/class-beans-options.php
  lib/api/options/functions.php
  lib/api/options/views/page.php
  lib/api/options/views/reset-notice-error.php
  lib/api/options/views/reset-notice-success.php
  lib/api/options/views/save-notice-error.php
  lib/api/options/views/save-notice-success.php
  tests/phpunit/integration/api/options/beans-options/processActions.php
  tests/phpunit/integration/api/options/beans-options/register.php
  tests/phpunit/integration/api/options/beans-options/renderMetabox.php
  tests/phpunit/integration/api/options/beans-options/renderPage.php
  tests/phpunit/integration/api/options/fixtures/test-options.php
  tests/phpunit/integration/api/options/includes/class-options-test-case.php
  tests/phpunit/unit/api/options/beans-options/register.php
  tests/phpunit/unit/api/options/beans-options/renderMetabox.php
  tests/phpunit/unit/api/options/beans-options/renderPage.php
  tests/phpunit/unit/api/options/beans-options/renderRenderNotice.php
  tests/phpunit/unit/api/options/beans-options/renderSaveNotice.php
  tests/phpunit/unit/api/options/fixtures/test-options.php
  tests/phpunit/unit/api/options/includes/class-options-test-case.php
Labels: Testing

#172 Replaced get_the_id with get_the_ID.
  lib/api/post-meta/functions.php
  tests/phpunit/unit/api/post-meta/beansGetPostMeta.php
Labels: Bug

#171 Added tests & improved documentation for beans_wrap_markup.
  lib/api/html/functions.php
  tests/phpunit/integration/api/html/beansWrapMarkup.php
  tests/phpunit/unit/api/html/beansWrapMarkup.php
  tests/phpunit/unit/api/html/fixtures/class-anonymous-action-stub.php
Labels: Documentation, Testing

#177 Tested beans_wrap_inner_markup.
  lib/api/html/functions.php
  tests/phpunit/integration/api/html/beansWrapInnerMarkup.php
  tests/phpunit/unit/api/html/beansWrapInnerMarkup.php
Labels: Documentation, Testing

#178 Refactored common WP stubs.
  tests/phpunit/unit/api/fields/includes/class-fields-test-case.php
  tests/phpunit/unit/api/html/beansAddAttributes.php
  tests/phpunit/unit/api/html/includes/class-html-test-case.php
  tests/phpunit/unit/api/image/includes/class-image-test-case.php
  tests/phpunit/unit/api/options/includes/class-options-test-case.php
  tests/phpunit/unit/class-test-case.php
Labels: Testing

#182 Optimized beans_get_post_meta
  lib/api/post-meta/functions.php
  tests/phpunit/unit/api/post-meta/beansGetPostMeta.php
Labels: Optimization

#183 Tested beans_output and beans_output_e
  lib/api/html/functions.php
  tests/phpunit/integration/api/html/beansOutput.php
  tests/phpunit/integration/api/html/beansOutputE.php
  tests/phpunit/unit/api/html/beansOutput.php
  tests/phpunit/unit/api/html/beansOutputE.php
Labels: Testing

#184 Fixed pagination.
  lib/templates/fragments/post.php
Labels: Bug

#185 Tested beans_remove_output
  lib/api/filters/functions.php
  lib/api/html/functions.php
  tests/phpunit/integration/api/html/beansRemoveOutput.php
  tests/phpunit/unit/api/html/beansRemoveOutput.php
  tests/phpunit/unit/api/html/fixtures/class-anonymous-filter-stub.php
Labels: Documentation, Testing

#186 Tested beans_open_markup and beans_open_markup_e
  lib/api/html/functions.php
  tests/phpunit/integration/api/html/beansOpenMarkup.php
  tests/phpunit/integration/api/html/beansOpenMarkupE.php
  tests/phpunit/unit/api/html/beansOpenMarkup.php
  tests/phpunit/unit/api/html/beansOpenMarkupE.php
Labels: Documentation, Testing

#188 Optimized _beans_when_has_action_do_render()
  lib/api/actions/functions.php
Labels: Optimization

#187 Tested & Improved beans_remove_markup
  lib/api/html/functions.php
  tests/phpunit/integration/api/html/beansRemoveMarkup.php
  tests/phpunit/unit/api/html/beansRemoveMarkup.php
Labels: Documentation, Testing

#189 Tested & Improved beans_close_markup and beans_close_markup_e
  lib/api/html/functions.php
  tests/phpunit/integration/api/html/beansCloseMarkup.php
  tests/phpunit/integration/api/html/beansCloseMarkupE.php
  tests/phpunit/integration/api/html/beansOpenMarkup.php
  tests/phpunit/integration/api/html/beansOpenMarkupE.php
  tests/phpunit/unit/api/html/beansCloseMarkup.php
  tests/phpunit/unit/api/html/beansCloseMarkupE.php
Labels: Documentation, Testing

#194 Tested beans_markup_markup
  lib/api/html/functions.php
  tests/phpunit/integration/api/html/beansModifyMarkup.php
  tests/phpunit/unit/api/html/beansModifyMarkup.php
Labels: Documentation, Testing

#195 Tested beans_reset_markup.
  lib/api/html/functions.php
  tests/phpunit/integration/api/html/beansResetMarkup.php
Labels: Documentation, Testing

#196 Escape HTML API
  lib/api/html/functions.php
  tests/phpunit/integration/api/html/beansCloseMarkup.php
  tests/phpunit/integration/api/html/beansOpenMarkup.php
Labels: Security

#197 Improved accessibility of Fields API and Beans Settings page
  lib/api/admin-menu.php
  lib/api/compiler/class-options.php
  lib/api/fields/assets/css/fields.css
  lib/api/fields/assets/css/fields.min.css
  lib/api/fields/functions.php
  lib/api/fields/types/field.php
  lib/api/fields/types/views/activation.php
  lib/api/fields/types/views/radio.php
  tests/phpunit/integration/api/fields/beansField.php
  tests/phpunit/integration/api/fields/types/beansFieldActivation.php
  tests/phpunit/integration/api/fields/types/beansFieldLabel.php
  tests/phpunit/integration/api/fields/types/beansFieldRadio.php
  tests/phpunit/unit/api/fields/types/beansFieldActivation.php
  tests/phpunit/unit/api/fields/types/beansFieldRadio.php
Labels: Accessibility

#199 Added unit tests for _Beans_Anonymous_Action
  lib/api/actions/class-beans-anonymous-action.php
  lib/api/actions/functions.php
  tests/phpunit/integration/api/html/beansWrapInnerMarkup.php
  tests/phpunit/integration/api/html/beansWrapMarkup.php
  tests/phpunit/unit/api/actions/beans-anonymous-action/__construct.php
  tests/phpunit/unit/api/actions/beans-anonymous-action/callback.php
  tests/phpunit/unit/api/html/fixtures/class-anonymous-action-stub.php
Labels: Testing

#200 Improved Compiler API Unit Tests.
  lib/api/compiler/class-beans-compiler.php
  tests/phpunit/unit/api/compiler/beans-compiler/addContentMediaQuery.php
  tests/phpunit/unit/api/compiler/beans-compiler/cacheFile.php
  tests/phpunit/unit/api/compiler/beans-compiler/cacheFileExist.php
  tests/phpunit/unit/api/compiler/beans-compiler/combineFragments.php
  tests/phpunit/unit/api/compiler/beans-compiler/fileystem.php
  tests/phpunit/unit/api/compiler/beans-compiler/formatContent.php
  tests/phpunit/unit/api/compiler/beans-compiler/get.php
  tests/phpunit/unit/api/compiler/beans-compiler/getExtension.php
  tests/phpunit/unit/api/compiler/beans-compiler/getFunctionContent.php
  tests/phpunit/unit/api/compiler/beans-compiler/getInternalContent.php
  tests/phpunit/unit/api/compiler/beans-compiler/getRemoteContent.php
  tests/phpunit/unit/api/compiler/beans-compiler/replaceCssUrl.php
  tests/phpunit/unit/api/compiler/beans-compiler/runCompiler.php
  tests/phpunit/unit/api/compiler/beans-compiler/setFilename.php
  tests/phpunit/unit/api/compiler/beans-compiler/setFragments.php
  tests/phpunit/unit/api/compiler/includes/class-compiler-test-case.php
  tests/phpunit/unit/class-test-case.php
Labels: Testing
