Repository Getbeans/Beans, pull requests merged in 2018-06, with the labels that each got.

#240 _Beans_Uikit improvements and unit tests.
  lib/api/components.php
  lib/api/uikit/class-beans-uikit.php
  lib/api/uikit/config/component-dependencies.php
  lib/api/utilities/functions.php
  tests/phpunit/unit/api/uikit/beans-uikit/getAllComponents.php
  tests/phpunit/unit/api/uikit/beans-uikit/getAutoloadComponents.php
  tests/phpunit/unit/api/uikit/beans-uikit/getComponentsFromDirectory.php
  tests/phpunit/unit/api/uikit/beans-uikit/getJsDirectories.php
  tests/phpunit/unit/api/uikit/beans-uikit/getLessDirectories.php
  tests/phpunit/unit/api/uikit/beans-uikit/registerJsComponents.php
  tests/phpunit/unit/api/uikit/beans-uikit/registerLessComponents.php
  tests/phpunit/unit/api/uikit/beans-uikit/toFilename.php
  tests/phpunit/unit/api/uikit/includes/class-uikit-test-case.php
  tests/phpunit/unit/api/utilities/beansJoinArrays.php
Labels: Documentation, Optimization, Quality, Testing

#244 Tests & Improvements for UIkit API enqueue components
  lib/api/uikit/class-beans-uikit.php
  lib/api/uikit/functions.php
  lib/api/utilities/functions.php
  tests/phpunit/integration/api/uikit/beansUikitAutoloadDependencies.php
  tests/phpunit/integration/api/uikit/beansUikitEnqueueComponents.php
  tests/phpunit/integration/api/uikit/includes/class-uikit-test-case.php
  tests/phpunit/unit/api/uikit/beansUikitEnqueueComponents.php
  tests/phpunit/unit/api/uikit/beansUikitGetAllComponents.php
  tests/phpunit/unit/api/uikit/beansUikitGetAllDependencies.php
  tests/phpunit/unit/api/utilities/beansArrayUnique.php
  tests/phpunit/unit/api/utilities/beansJoinArraysClean.php
Labels: Optimization, Quality, Testing

#243 Added skip links.
  lib/api/components.php
  lib/api/html/accessibility.php
  lib/api/html/assets/js/skip-link-fix.js
  lib/api/layout/functions.php
  lib/assets/less/style.less
  lib/templates/fragments/menu.php
  lib/templates/structure/content.php
  lib/templates/structure/header.php
  lib/templates/structure/sidebar-primary.php
  lib/templates/structure/sidebar-secondary.php
  tests/phpunit/integration/api/html/beansBuildSkipLinks.php
  tests/phpunit/integration/api/html/includes/class-html-test-case.php
  tests/phpunit/integration/api/layout/beansHasPrimarySidebar.php
  tests/phpunit/integration/api/layout/beansHasSecondarySidebar.php
  tests/phpunit/integration/api/template/beansLoadDefaultTemplate.php
  tests/phpunit/unit/api/html/beansBuildSkipLinks.php
  tests/phpunit/unit/api/html/includes/class-html-test-case.php
  tests/phpunit/unit/api/layout/beansHasPrimarySidebar.php
  tests/phpunit/unit/api/layout/beansHasSecondarySidebar.php
Labels: Accessibility

#250 Changed Beans version from 1.4.1 to 1.5.0-beta.
  lib/init.php
  style.css
Labels: Documentation

#251 Added Compiler Tests. Added new utility functions.
  lib/api/compiler/class-beans-compiler.php
  lib/api/compiler/functions.php
  lib/api/uikit/class-beans-uikit.php
  lib/api/uikit/functions.php
  lib/api/utilities/functions.php
  tests/phpunit/integration/api/compiler/beans-compiler/cacheFile.php
  tests/phpunit/integration/api/compiler/beans-compiler/combineFragments.php
  tests/phpunit/integration/api/compiler/beans-compiler/formatContent.php
  tests/phpunit/integration/api/compiler/beans-compiler/runCompiler.php
  tests/phpunit/integration/api/compiler/beansCompileCssFragments.php
  tests/phpunit/integration/api/compiler/beansCompileJsFragments.php
  tests/phpunit/integration/api/compiler/beansCompileLessFragments.php
  tests/phpunit/integration/api/compiler/beansFlushCompiler.php
  tests/phpunit/integration/api/compiler/includes/class-compiler-test-case.php
  tests/phpunit/unit/api/compiler/beans-compiler/combineFragments.php
  tests/phpunit/unit/api/compiler/beans-compiler/filesystem.php
  tests/phpunit/unit/api/compiler/beans-compiler/formatContent.php
  tests/phpunit/unit/api/compiler/beans-compiler/runCompiler.php
  tests/phpunit/unit/api/compiler/beansCompileCssFragments.php
  tests/phpunit/unit/api/compiler/beansCompileJsFragments.php
  tests/phpunit/unit/api/compiler/beansCompileLessFragments.php
  tests/phpunit/unit/api/compiler/beansCompilerAddFragment.php
  tests/phpunit/unit/api/compiler/beansFlushCompiler.php
  tests/phpunit/unit/api/compiler/includes/class-base-test-case.php
  tests/phpunit/unit/api/uikit/beansUikitRegisterTheme.php
  tests/phpunit/unit/api/utilities/beansScandir.php
  tests/phpunit/unit/api/utilities/beansStrEndsWith.php
  tests/phpunit/unit/api/utilities/beansStrStartsWith.php
Labels: Enhancement, Optimization, Testing

#253 Improved UIkit API compiling. Added tests.
  lib/api/uikit/class-beans-uikit.php
  tests/phpunit/integration/api/uikit/beans-uikit/compile.php
  tests/phpunit/integration/api/uikit/beansUikitEnqueueAssets.php
  tests/phpunit/integration/api/uikit/fixtures/less/alert.less
  tests/phpunit/integration/api/uikit/fixtures/less/close.less
  tests/phpunit/integration/api/uikit/fixtures/less/panel.less
  tests/phpunit/integration/api/uikit/fixtures/less/uikit.less
  tests/phpunit/integration/api/uikit/fixtures/less/variables.less
  tests/phpunit/integration/api/uikit/includes/class-uikit-test-case.php
  tests/phpunit/unit/api/uikit/beans-uikit/compile.php
Labels: Optimization, Testing

#256 Fixed whitespace bug in compiler
  lib/api/compiler/class-beans-compiler.php
  tests/phpunit/integration/api/uikit/beans-uikit/compile.php
Labels: Bug

#257 Updated languages POT file.
  lib/languages/tm-beans.pot
  style.css
Labels: Internationalization

#262 Fixed and improved the Preview Tooling for Customizer
  lib/admin/assets/js/wp-customize-preview.js
  lib/admin/wp-customize.php
  lib/api/fields/assets/js/fields.js
  lib/api/fields/assets/js/fields.min.js
  lib/api/wp-customize/class-beans-wp-customize.php
Labels: Bug

#263 Updated pot file from Customizer fix.
  lib/languages/tm-beans.pot
Labels: Internationalization

#264 Add CHANGELOG.md
  CHANGELOG.md
Labels: Documentation
