Repository Getbeans/Beans, pull requests merged in 2018-02, with the labels that each got.

#119 Fixed Test Suites
  phpunit.xml.dist
  tests/phpunit/integration/api/actions/includes/class-actions-test-case.php
  tests/phpunit/integration/api/actions/includes/class-replace-action-test-case.php
  tests/phpunit/integration/api/filters/includes/class-filters-test-case.php
  tests/phpunit/integration/integrationSample.php
  tests/phpunit/integration/phpunit.xml.dist
  tests/phpunit/unit/api/actions/includes/class-actions-test-case.php
  tests/phpunit/unit/api/actions/includes/class-replace-action-test-case.php
  tests/phpunit/unit/api/filters/includes/class-filters-test-case.php
Labels: Testing

#120 Made the Template API WPCS compliant & tested.
  lib/api/template/functions.php
  phpunit.xml.dist
  tests/phpunit/integration/api/template/beansLoadDefaultTemplate.php
  tests/phpunit/integration/api/template/beansLoadFragmentFile.php
  tests/phpunit/unit/api/template/beansLoadDefaultTemplate.php
  tests/phpunit/unit/api/template/beansLoadFragmentFile.php
  tests/phpunit/unit/api/template/includes/class-template-test-case.php
Labels: Compliance, Documentation, Testing

#123 WPCS Compliance - Files in lib\admin
  lib/admin/options.php
  lib/admin/updater.php
  lib/admin/wp-customize.php
Labels: Compliance

#124 Made lib\api\compiler WPCS compliant
  lib/api/compiler/class-options.php
  lib/api/compiler/class-page-compiler.php
Labels: Compliance

#126 Made lib\api\image WPCS compliant
  lib/api/image/class-options.php
  lib/api/image/functions.php
Labels: Compliance

#134 Made lib\api files WPCS compliant
  lib/api/admin-menu.php
  lib/api/components.php
  lib/api/init.php
Labels: Documentation

#131 Made lib\api\uikit WPCS compliant
  lib/api/uikit/class.php
  lib/api/uikit/functions.php
Labels: Compliance

#135 Added tests for beans_get_post_meta().
  lib/api/post-meta/functions.php
  tests/phpunit/integration/api/post-meta/beansGetPostMeta.php
  tests/phpunit/unit/api/post-meta/beansGetPostMeta.php
Labels: Testing

#145 Upgrade PHPCS/WPCS
  composer.json
  lib/api/actions/class-beans-anonymous-action.php
  lib/api/compiler/class-page-compiler.php
  lib/api/init.php
  lib/api/utilities/functions.php
  lib/api/utilities/polyfills.php
  lib/api/widget/functions.php
  lib/api/wp-customize/class.php
  tests/phpunit/integration/api/actions/includes/class-actions-test-case.php
  tests/phpunit/integration/api/filters/includes/class-filters-test-case.php
  tests/phpunit/integration/bootstrap.php
  tests/phpunit/unit/api/actions/beansRenderAction.php
  tests/phpunit/unit/api/actions/stubs/class-action-stub.php
  tests/phpunit/unit/api/utilities/beansRenderFunction.php
  tests/phpunit/unit/api/utilities/beansRenderFunctionArray.php
  tests/phpunit/unit/bootstrap.php
  tests/phpunit/unit/class-test-case.php
Labels: Compliance

#114 Made HTML attribute add, remove, replace WPCS compliant. Added tests.
  lib/api/components.php
  lib/api/html/class-beans-attribute.php
  lib/api/html/class.php
  lib/api/html/functions.php
  tests/phpunit/integration/api/html/beansAddAttribute.php
  tests/phpunit/integration/api/html/beansRemoveAttribute.php
  tests/phpunit/integration/api/html/beansReplaceAttribute.php
  tests/phpunit/integration/api/html/fixtures/test-markup.php
  tests/phpunit/integration/api/html/includes/class-html-test-case.php
  tests/phpunit/unit/api/html/beansAddAttribute.php
  tests/phpunit/unit/api/html/beansRemoveAttribute.php
  tests/phpunit/unit/api/html/beansReplaceAttribute.php
  tests/phpunit/unit/api/html/fixtures/test-markup.php
  tests/phpunit/unit/api/html/includes/class-html-test-case.php
Labels: Documentation, Enhancement, Testing
